# Generated by Django 3.1.7 on 2021-02-28 00:27

import datetime
from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prep', models.DurationField(default=datetime.timedelta(seconds=1800))),
                ('cook', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('servings', models.IntegerField(default=1)),
                ('image', models.ImageField(upload_to='media/')),
                ('ingredients', markdownx.models.MarkdownxField()),
                ('directions', markdownx.models.MarkdownxField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
