# Generated by Django 3.1.7 on 2021-02-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210228_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep',
            field=models.DurationField(),
        ),
    ]
