# Generated by Django 3.1.7 on 2021-02-28 02:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210228_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
