# Generated by Django 3.1.7 on 2021-02-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210228_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep',
            field=models.CharField(max_length=255),
        ),
    ]
